config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  
  root 'static_pages#home'
  
  get 'help' => 'static_pages#help'
  
  get 'about' => 'static_pages#about'
  
  get 'contact' => 'static_pages#contact'
  
  get 'news' => 'static_pages#news'
  
  get 'signup' => 'users#new'
  
  get 'login' => 'sessions#new'
  
  post 'login' => 'sessions#create'
  
  delete 'logout' => 'sessions#destroy'
  
  resources :users do 
    member do 
      get :following, :followers 
    end
    
  end
  
  resources :account_activations, only: [:edit]
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :microposts, only: [:create, :destroy]
  
  resources :relationships, only: [:create, :destroy]

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if is_logged_in?
      @micropost = current_user.microposts.build 
      @feed_items = current_user.feed.paginate(page: params[:page], per_page: 20)
    end  
  end

  def help
  end
  
  def about
  end
  
  def contact 
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title,"About") %>
<h1>About Us</h1>
<p>We are a social media platform dedicated to bringing people together, and bridging time and space.</p>

app/views/static_pages/contact.html.erb
<% provide(:title,"Contact") %>
<h1>Contact Us</h1>
<p>Please don't hesitate to drop us a line if you need help.</p>

app/views/static_pages/help.html.erb
<% provide(:title,"Help") %>
<h1>SharedTalk</h1>
<p>We are here 24/7 to help you with any problems you might encounter.</p>

app/views/static_pages/home.html.erb
<% provide(:title,"Home")%>
<% if is_logged_in? %>
  <div class="row">
      <aside class="col-md-4">
          <section class="user_info">
            <%= render 'shared/user_info' %>  
          </section>
          <section class="">
            <%= render 'shared/stats' %>
          </section>
          <section class="micropost_form">
            <%= render 'shared/micropost_form' %>  
          </section>
      </aside>
      <div class="col-md-8 user-posts">
        <%= render 'shared/feed' %>
      </div>
  </div>
<% else %>
<div class="jumbotron center">
<h1 class="welcome">Welcome to SharedTalk</h1>
<h3>Making connections that matter!</h3>
<%= link_to "Sign Up!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<% end %>