config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  
  root 'static_pages#home'
  
  get 'help' => 'static_pages#help'
  
  get 'about' => 'static_pages#about'
  
  get 'contact' => 'static_pages#contact'
  
  get 'news' => 'static_pages#news'
  
  get 'signup' => 'users#new'
  
  get 'login' => 'sessions#new'
  
  post 'login' => 'sessions#create'
  
  delete 'logout' => 'sessions#destroy'
  
  resources :users do 
    member do 
      get :following, :followers 
    end
    
  end
  
  resources :account_activations, only: [:edit]
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :microposts, only: [:create, :destroy]
  
  resources :relationships, only: [:create, :destroy]

  

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, :valid_user?, :check_expiration, only: [:edit,:update]
  
  def new
  end

  def edit
  end
  
  def update
    if params[:user][:password].empty?
      flash.now[:danger] = "Password can't be empty"
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in(@user)
      flash[:success] = "Password has been reset"
      redirect_to @user
    else
      render 'edit'
    end  
  end
  
  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = 'Email sent with password reset instructions'
      redirect_to root_url 
    else
      flash[:danger] = 'Email address not found'
      render 'new'
    end  
    
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
  # Before Filters
  
  # Find user
  def get_user
    @user = User.find_by(email: params[:email])
  end
  
  # Confirms a valid user
  def valid_user?
    unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]))
      redirect_to root_url
    end  
  end
  
  # Check expiration of reset token 
  def check_expiration
    if @user.password_reset_expired?
      flash[:danger] = "Password reset has expired"
      redirect_to new_password_reset_url
    end
  end  
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<%= provide(:title,'Reset Password') %>
<h3>Forgot password?</h3>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
          <!--Pass the form varibale to the partial & access associated object via f.object-->
          <%= render 'shared/error_messages', object: f.object %>
          <%= hidden_field_tag :email, @user.email %>
          <div class="field">
            <%= f.label :password %>
            <%= f.password_field :password %>
          </div>
          <div class="field">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation %>
          </div>
          <div class="field">
            <%= f.submit "Update Password", class: 'btn btn-primary' %>
          </div>
        <% end %>
    </div>
</div>

app/views/password_resets/new.html.erb
<%= provide(:title, 'Forgot Password') %>
<h3>Forgot Password</h3>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(:password_reset, url: password_resets_path)  do |f| %>
          <div class="field">
            <%= f.label :email %>
            <%= f.email_field :email %>
          </div>
          <div class="field">
            <%= f.submit 'Submit', class: 'btn btn-primary' %>
          </div>
        <% end %>
    </div>
</div>