config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  
  root 'static_pages#home'
  
  get 'help' => 'static_pages#help'
  
  get 'about' => 'static_pages#about'
  
  get 'contact' => 'static_pages#contact'
  
  get 'news' => 'static_pages#news'
  
  get 'signup' => 'users#new'
  
  get 'login' => 'sessions#new'
  
  post 'login' => 'sessions#create'
  
  delete 'logout' => 'sessions#destroy'
  
  resources :users do 
    member do 
      get :following, :followers 
    end
    
  end
  
  resources :account_activations, only: [:edit]
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :microposts, only: [:create, :destroy]
  
  resources :relationships, only: [:create, :destroy]

  

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error-explanation">
    <div class="alert alert-danger">
        <p>This form contains <%= pluralize(object.errors.count, "error") %></p>
    </div>
    <ul>
        <% object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %> 

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>  
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost, html: { multipart: true} do |f| %>
<!--Pass the form varibale to the partial & access associated object via f.object-->
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
      <%= f.text_area :content, placeholder: 'Compose new micropost...' %>
  </div>
  <div class="field">
      <%= f.submit "Post", class: "btn btn-primary" %>
  </div>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<!--<script type="text/javascript">-->
<!--  $('#micropost_picture').on("change",function(){-->
<!--    alert('Hello');-->
<!--  })-->
<!--</script>-->

app/views/shared/_stats.html.erb
<%  @user ||= current_user %>
<div class="stats">
    <a href="<%= following_user_path(@user) %>">
      <strong class="stat" id="following">
        <%= @user.following.count %>
      </strong>
      Following
    </a>
    <a href="<%= followers_user_path(@user) %>">
      <strong class="stat" id="followers">
        <%= @user.followers.count %>  
      </strong>
      Followers
    </a>
</div>

app/views/shared/_user_info.html.erb
<section class="user-info-heading">
  <%= link_to gravatar_for(current_user,size: 50), current_user %>
  <h4><%= current_user.name %></h4>
</section>  
<span><%= link_to "View My Profile", current_user%> |</span>
<span class="micropost-count"><%= pluralize(current_user.microposts.count, "micropost") %></span>