config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  
  root 'static_pages#home'
  
  get 'help' => 'static_pages#help'
  
  get 'about' => 'static_pages#about'
  
  get 'contact' => 'static_pages#contact'
  
  get 'news' => 'static_pages#news'
  
  get 'signup' => 'users#new'
  
  get 'login' => 'sessions#new'
  
  post 'login' => 'sessions#create'
  
  delete 'logout' => 'sessions#destroy'
  
  resources :users do 
    member do 
      get :following, :followers 
    end
    
  end
  
  resources :account_activations, only: [:edit]
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :microposts, only: [:create, :destroy]
  
  resources :relationships, only: [:create, :destroy]

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <nav class="center">
      <ul>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "News", news_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
     <nav>
       <%= link_to "SharedTalk", "/", id: "logo" %>
       <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "Home",root_path %></li>
         <li><%= link_to "Help", help_path %></li>
         <% if is_logged_in? %>
           <li><%= link_to "Users", users_path %></li>
           <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                   Account<b class="caret"></b>
               </a>
               <ul class="dropdown-menu">
                   <li><%= link_to "Profile", user_path(current_user) %></li>
                   <li><%= link_to "Setting", "#" %></li>
                   
                   <li><%= link_to "Log Out", logout_path, method: "delete" %></li>
               </ul>
           </li>
         <% else %>
         <li><%= link_to "Log In", login_path %></li>
         <% end %>
       </ul>
     </nav>
  </div>
</header>

app/views/layouts/_shimv.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield :title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render "layouts/shimv" %>
</head>
<body>
<%= render "layouts/header" %>
<div class="container">
  <% flash.each do |message_type, message| %>
    <!--<div class="alert alert-<%#= message_type%>"><%#= message %></div>-->
    <!-- This is a much cleaner code using 'content_tag' helper-->
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %> 
  <% end %>  
  <%= yield %>
</div>
<%= render "layouts/footer" %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>